# Generated by rebar3_nix
let fetchOnly = { src, ... }: src;
in { builder ? fetchOnly, fetchHex, fetchgit, fetchFromGitHub, overrides ? (x: y: { }) }:
let
  self = packages // (overrides self packages);
  packages = with self; {
    unicode_util_compat = builder {
      name = "unicode_util_compat";
      version = "0.7.0";
      src = fetchHex {
        pkg = "unicode_util_compat";
        version = "0.7.0";
        sha256 = "sha256-Je7m1n32GWDPanlCOVZlmbCeF+Zo03ACR7xJhjgVJSE=";
      };
      beamDeps = [ ];
    };
    ssl_verify_fun = builder {
      name = "ssl_verify_fun";
      version = "1.1.7";
      src = fetchHex {
        pkg = "ssl_verify_fun";
        version = "1.1.7";
        sha256 = "sha256-/kwZDo83QB0wFnyMQF7aGUafNFd5h8dt3mE+g4u8Z/g=";
      };
      beamDeps = [ ];
    };
    parse_trans = builder {
      name = "parse_trans";
      version = "3.4.1";
      src = fetchHex {
        pkg = "parse_trans";
        version = "3.4.1";
        sha256 = "sha256-YgpAbOddragnuC5FPBnPBndr4mb1pnz/NOHvLLtg5Jo=";
      };
      beamDeps = [ ];
    };
    mimerl = builder {
      name = "mimerl";
      version = "1.2.0";
      src = fetchHex {
        pkg = "mimerl";
        version = "1.2.0";
        sha256 = "sha256-8nhYVlCqWBmGJkY46/aY+LsZ3yl/Zq2RsYkQ38bhkyM=";
      };
      beamDeps = [ ];
    };
    metrics = builder {
      name = "metrics";
      version = "1.0.1";
      src = fetchHex {
        pkg = "metrics";
        version = "1.0.1";
        sha256 = "sha256-abCa3dxPdKQHFq5U0UD5O+sPuJeNhjbq3tDDG28JnxY=";
      };
      beamDeps = [ ];
    };
    idna = builder {
      name = "idna";
      version = "6.1.1";
      src = fetchHex {
        pkg = "idna";
        version = "6.1.1";
        sha256 = "sha256-kjdut4lEEu0ZrEdeSob3tBPBufu1vRbczVeTQVeUTOo=";
      };
      beamDeps = [ unicode_util_compat ];
    };
    certifi = builder {
      name = "certifi";
      version = "2.12.0";
      src = fetchHex {
        pkg = "certifi";
        version = "2.12.0";
        sha256 = "sha256-7mjYXfIuVUBAzbS+EA8zhzrGBROHuvao9s6CJyNA/xw=";
      };
      beamDeps = [ ];
    };
    jsx = builder {
      name = "jsx";
      version = "3.1.0";
      src = fetchHex {
        pkg = "jsx";
        version = "3.1.0";
        sha256 = "sha256-DFzI/cEbU8wlz2WsZwWtOeVOzFbRwi5K249aU/uUJ/M=";
      };
      beamDeps = [ ];
    };
    hackney = builder {
      name = "hackney";
      version = "1.19.1";
      src = fetchHex {
        pkg = "hackney";
        version = "1.19.1";
        sha256 = "sha256-iqCCNL3vwmmZXGPCKCzzzQ42/r46a/qxG2EFcv3RytA=";
      };
      beamDeps = [ certifi idna metrics mimerl parse_trans ssl_verify_fun unicode_util_compat ];
    };
  };
in self
