jobs:
  build:
    name: "Blockfrost Erlang"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "cachix/install-nix-action@v24"
        with:
          nix_path: "nixpkgs=channel:nixos-unstable"

      - name: Nix build
        run: nix-build

      - name: Dialyzer
        run: nix-shell --run "rebar3 dialyzer"

name: Blockfrost Erlang CI
"on":
  pull_request: {}
  push: {}
  workflow_dispatch: {} # Enables manual triggering of the workflow

